# Generated by Django 6.0.5 on 2026-05-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
